DWA_params:
  max_speed:
    type: double
    default_value: 1.2
  min_speed:
    type: double
    default_value: 0.0
  max_accel:
    type: double
    default_value: 1.5
  max_decel:
    type: double
    default_value: -1.5
  max_yaw_rate:
    type: double
    default_value: 1.0
  min_yaw_rate:
    type: double
    default_value: -1.0
  max_yaw_accel:
    type: double
    default_value: 2.5
  max_yaw_decel:
    type: double
    default_value: -2.5
  min_turning_radius:
    type: double
    default_value: 0.3
  heading_coeff:
    type: double
    default_value: 0.6
  obstacle_coeff:
    type: double
    default_value: 0.8
  velocity_coeff:
    type: double
    default_value: 0.2
  energy_coeff:
    type: double
    default_value: 0.05
  time_horizon:
    type: double
    default_value: 1.2
  velocity_samples:
    type: int
    default_value: 10